=== RMI/OPGEEv4/opgee/etc/opgee.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs='http://www.w3.org/2001/XMLSchema' elementFormDefault='qualified'>
	
	<xs:element name='Model'>
		<xs:complexType>
			<xs:choice maxOccurs="2">
				<xs:element minOccurs='0' maxOccurs='1' ref="Analysis"/>
				<xs:element minOccurs='0' maxOccurs='1' ref='TechnologyDatabase'/>
			</xs:choice>
		</xs:complexType>
    </xs:element>
	
    <xs:element name='FunctionalUnit' type='xs:NCName'/>
    <xs:element name='EnergyBasis' type='xs:NCName'/>
	
	<xs:element name='Analysis'>
        <xs:complexType>
			<xs:choice maxOccurs='unbounded'>
                <xs:element minOccurs='1' maxOccurs='1' ref='FunctionalUnit'/>
                <xs:element minOccurs='1' maxOccurs='1' ref='EnergyBasis'/>
                <xs:element minOccurs='0' maxOccurs='unbounded' ref='Field'/>
                <xs:element ref='Variables'/>
            </xs:choice>
            <xs:attribute name='name' use='required' type='xs:NCName'/>
        </xs:complexType>
	</xs:element>
	
    <xs:element name='Variables'>
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs='unbounded' ref='A'/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
	
	<xs:element name='Field'>
        <xs:complexType>
            <xs:choice maxOccurs='unbounded'>
                <xs:element maxOccurs='unbounded' ref='A'/>
                <xs:element minOccurs='1' maxOccurs='unbounded' ref='Process'/>
            </xs:choice>
            <xs:attribute name='is_offshore' use='required' type='xs:NCName'/>
            <xs:attribute name='location' use='required' type='xs:NCName'/>
            <xs:attribute name='name' use='required' type='xs:NCName'/>
        </xs:complexType>
    </xs:element>
	
    <xs:element name='A'>
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base='xs:NMTOKEN'>
                    <xs:attribute name='name' use='required' type='xs:NCName'/>
                    <xs:attribute name='type' type='xs:NCName'/>
                    <xs:attribute name='unit'/>
                    <xs:attribute name='desc'/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
	</xs:element>
	
	<!-- use type forward reference to define recursive structure -->
	<xs:element name="Process" type="ProcessType"></xs:element>
	
	<xs:complexType name="ProcessType">
		<xs:choice maxOccurs="unbounded">
			<xs:element name="Process" type="ProcessType"/>
			<xs:element minOccurs='0' maxOccurs='unbounded' ref='A'/>
			<xs:element minOccurs='0' maxOccurs='unbounded' ref='Technology'/>	
			<xs:element minOccurs='0' maxOccurs='unbounded' ref='Option'/>
			<xs:element minOccurs='0' maxOccurs='unbounded' ref='Stream'/>			
		</xs:choice>
		<xs:attribute name='class' type='xs:NCName'/>
		<xs:attribute name='name' type='xs:NCName'/>
	</xs:complexType>
	
    <xs:element name='Option'>
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs='unbounded' ref='Technology'/>
            </xs:sequence>
            <xs:attribute name='default' use='required' type='xs:NCName'/>
            <xs:attribute name='name' use='required' type='xs:NCName'/>
            <xs:attribute name='selected' use='required' type='xs:NCName'/>
        </xs:complexType>
	</xs:element>
	
	<xs:element name='Temperature'>
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base='xs:decimal'>
                    <xs:attribute name='unit' use='required'/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
	</xs:element>	
	
	<xs:element name='Pressure'>
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base='xs:decimal'>
                    <xs:attribute name='unit' use='required'/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>	
	
    <xs:element name='Stream'>
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element ref='Temperature'/>
                <xs:element ref='Pressure'/>
                <xs:element ref='Component'/>
                <xs:element ref='Source'/>
                <xs:element ref='Destination'/>
            </xs:choice>
            <xs:attribute name='name' use='required'/>
            <xs:attribute name='number' use='required' type='xs:integer'/>
        </xs:complexType>
	</xs:element>
	
    <xs:element name='Phase' type='xs:NCName'/>
	
	<xs:element name='Rate'>
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base='xs:decimal'>
                    <xs:attribute name='unit' use='required'/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>	
	
	<xs:element name='Component'>
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element minOccurs="1" ref='Phase'/>
                <xs:element minOccurs="1" ref='Rate'/>
			</xs:choice>
			<xs:attribute name='name' use='required'/>
        </xs:complexType>
	</xs:element>
	
    <xs:element name='Source'>
        <xs:complexType>
            <xs:attribute name='name' use='required' type='xs:NCName'/>
        </xs:complexType>
    </xs:element>
	
	<xs:element name='Destination'>
        <xs:complexType>
            <xs:attribute name='fraction' type='xs:decimal'/>
            <xs:attribute name='name' use='required' type='xs:NCName'/>
        </xs:complexType>
    </xs:element>
	
	<xs:element name='Technology'>
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs='0' maxOccurs='unbounded' ref='A'/>
            </xs:sequence>
            <xs:attribute name='class' use='required' type='xs:NCName'/>
            <xs:attribute name='name' type='xs:NCName'/>			
        </xs:complexType>
	</xs:element>
	
	<xs:element name='TechnologyDatabase'>
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs='0' maxOccurs='unbounded' ref='Technology'/>
			</xs:sequence>
		</xs:complexType>		
	</xs:element>
	
</xs:schema>

=== RMI/OPGEEv4/tests/files/test_stream.xml
<?xml version="1.0" encoding="UTF-8"?>
<Model xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../opgee/etc/opgee.xsd">
	<Analysis name="test">
		<A name="functional_unit">oil</A>
		<A name="energy_basis">LHV</A>
		<Field name="test"/>
	</Analysis>

	<Field name="test">
		<A name="country">USA</A>
		<A name="offshore">0</A>
		<A name="age">86</A>
		<A name="depth">4936</A>
		<A name="oil_prod">101295</A>
		<A name="num_prod_wells">41539</A>
		<A name="num_water_inj_wells">34426</A>
		<A name="well_diam">3.01</A>
		<A name="prod_index">37.53</A>
		<A name="res_press">887.31</A>
		<A name="res_temp">70.84</A>
		<A name="GOR">1205.4</A>

		<Process class="Proc1" desc="Test process 1"/>
		<Process class="Proc2" desc="Test process 2"/>
		<Process class="Proc3" desc="Test process 3"/>
		<Process class="Proc4" desc="Test process 4"/>

		<Stream src="Proc1" dst="Proc2" name="stream1">
			<Contains>crude oil</Contains>
		</Stream>

		<!-- Creates a process loop -->
		<Stream src="Proc2" dst="Proc3">
			<Contains>natural gas</Contains>
		</Stream>

		<Stream src="Proc3" dst="Proc2">
			<Contains>hydrogen</Contains>
		</Stream>

		<Stream src="Proc3" dst="Proc4">
			<Contains>CO2</Contains>
			<Contains>hydrogen</Contains>
		</Stream>

		<Stream src="Proc4" dst="Environment" boundary="Production"/>

	</Field>
</Model>

=== RMI/OPGEEv4/tests/files/test_run_subcmd.xml
<Model xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../opgee/etc/opgee.xsd">

	<Analysis name="test">
		<A name="functional_unit">oil</A>
		<A name="boundary">Production</A>
		<A name="GWP_horizon">100</A>
		<A name="GWP_version">AR5</A>
		<Field name="test"/>
	</Analysis>

	<Field name="test">
		<Process class="ProcA" desc="Test process 1"/>
		<Process class="ProcB" desc="Test process 2"/>

		<Process class="Boundary" boundary="Production"/>

		<Stream src="ProcA" dst="ProcB">
			<Contains>crude oil</Contains>
		</Stream>

		<Stream	src="ProcB" dst="ProductionBoundary">
			<A name="temperature">90.0</A>
			<A name="pressure">150.0</A>
			<Component name="oil" phase="liquid">100</Component>
			<Contains>crude oil</Contains>
		</Stream>
	</Field>

</Model>

=== RMI/OPGEEv4/tests/files/test_boundary.xml
<?xml version="1.0" encoding="UTF-8"?>
<Model xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../opgee/etc/opgee.xsd">

	<Analysis name="test_boundary">
		<A name="functional_unit">oil</A>
		<A name="energy_basis">LHV</A>
	  <A name="GWP_horizon">100</A>
	  <A name="GWP_version">AR5</A>
		<Field name="test_gas_transmission_boundary"/>
	</Analysis>
    
    <Field name="test_gas_transmission_boundary">

		<Process class="Before"/>
        <Process class="GasProductionSiteBoundary"/>
        <Process class="TransmissionCompressor"/>
        
        <Stream src="Before" dst="GasProductionSiteBoundary" name="before to production site boundary">
            <Component name="N2" phase="gas">25.7</Component>
			<Component name="CO2" phase="gas">0.2</Component>
			<Component name="C1" phase="gas">435.0</Component>
			<Component name="C2" phase="gas">51.3</Component>
			<Component name="C3" phase="gas">5.3</Component>
			<Component name="C4" phase="gas">1.4</Component>
			<A name="temperature">90.0</A>
			<A name="pressure">500.0</A>
			<Contains>gas for production site boundary</Contains>
		</Stream>
        
        <Stream src="GasProductionSiteBoundary" dst="TransmissionCompressor" name="production site boundary to transmission compressor">
			<Contains>gas for transmission compressor</Contains>
		</Stream>
    
    
    </Field>

</Model>

=== RMI/OPGEEv4/opgee/etc/opgee.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Working draft of XML file format -->

<!-- This file contains the standard OPGEEv4 LCA model. The metadata describintg fields, options,
     and default values is found in attributes.xml. When creating a new model, the user can start
     with the standard model and add/delete/alter elements in a separate file, or simply save copy
     and modify this file. We also (will) support site- and user-specific XML template files that
     define custom starting points.
     -->
<Model xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
       xsi:noNamespaceSchemaLocation="opgee.xsd">
	<Analysis name="default">
		<!-- Global parameters -->
		<FunctionalUnit>oil</FunctionalUnit>
		<EnergyBasis>LHV</EnergyBasis>
		
		<!-- Are variables different than parameters? -->
		<!-- Are variables all global to the Analysis, or stored per element, e.g., Field, or both? -->
		<Variables>
			<A name="v1" type="float" unit="kWh/day">123.5</A>
			<A name="v2" unit="zzz">434</A>
		</Variables>

		<Field name="US_FW">
			<A name="location">USA</A>
			<A name="is_offshore">0</A>
			<A name="age">86</A>
			<A name="depth">4936</A>
			<A name="oil_prod">101295</A>
			<A name="num_prod_wells">41539</A>
			<A name="num_water_inj_wells">34426</A>
			<A name="well_diam" >3.01</A>
			<A name="prod_index">37.53</A>
			<A name="res_press">887.31</A>
			<A name="res_temp">70.84</A>
			
			<!-- Where should Streams be defined? At the field level? Within the Process
			     that consumes them? (That should be unique, right?) Is there any need to
			     specify the source or destination then?
			     -->
			<Stream number="1" name="oil in reservoir" src="_" dst="ReservoirWellInterface">
				<Temperature unit="degF">70.8</Temperature>
				<Pressure unit="psia">887.3</Pressure>
				<Component name="oil" phase="liquid" unit="tonne/d">14555.9</Component>
				<Component name="H2O" phase="liquid" unit="tonne/d">2037.8</Component>
			</Stream>
			
			<Stream number="100" name="water in reservoir" src="_" dst="ReservoirWellInterface">
				<Temperature unit="degF">70.8</Temperature>
				<Pressure unit="psia">887.3</Pressure>
				<Component name="H2O" phase="liquid" unit="tonne/d">255636.1</Component>
			</Stream>
			
			<Stream number="25" name="gas from reservoir" src="_" dst="ReservoirWellInterface">
				<Temperature unit="degF">70.8</Temperature>
				<Pressure unit="psia">887.3</Pressure>
				<Component name="N2" phase="gas" unit="tonne/d">519.9</Component>
				<Component name="CO2" phase="gas" unit="tonne/d">8858.8</Component>
				<Component name="CH4" phase="gas" unit="tonne/d">22288.1</Component>
				<Component name="C2H6" phase="gas" unit="tonne/d">4495.1</Component>
				<Component name="C3H8" phase="gas" unit="tonne/d">4399.9</Component>
				<Component name="C4H10" phase="gas" unit="tonne/d">284.4</Component>
				<Component name="H2S" phase="gas" unit="tonne/d">1.5</Component>
			</Stream>
			
			<Aggregator name="Exploration_and_development">
				<Aggregator name="Exploration">
					<Process class="SurveyVehicle">
						<A name="type">ship</A>
						<A name="vehicle_weight" unit="tons">124</A>
						<A name="distance" unit="mi">2342</A>
					</Process>
					<Process class="SurveyVehicle">
						<A name="type">truck</A>
						<A name="vehicle_weight" unit="tons">123</A>
						<A name="distance" unit="mi">2342</A>
					</Process>
				</Aggregator>
				<Aggregator name="FieldDevelopment">
					<Process class="Drilling">
						<A name="productivity">medium</A>
						<A name="total_wells">2500</A>
					</Process>
					
					<Process class="ReservoirWellInterface">
						<A name="x">0</A>
					</Process>
					
					<Process class="LandUse"/>
				</Aggregator>
				<Process class="Fracking"/>
			</Aggregator>
			<Aggregator name="Production_Stage">
				<Process class="FluidProduction"/>
				<Process class="FluidInjection"/>
				<Process class="BitumenMining"/>
				<Process class="Maintenance"/>
			</Aggregator>
			<Aggregator name="SurfaceProcessing_Stage">
				<Process class="CrudeSeparationAndHandling"/>
				<Process class="CrudeStorage"/>
				<Process class="BitumenUpgradingOrDistilation"/>
				<Process class="WasteTreatmentAndDisposal"/>
			</Aggregator>
			<Aggregator name="Transport_Stage">
				<Process class="CrudeTransport"/>
			</Aggregator>
		</Field>
	</Analysis>
</Model>

=== RMI/OPGEEv4/tests/files/test_separator.xml
<?xml version="1.0" encoding="UTF-8"?>
<Model xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../opgee/etc/opgee.xsd">

	<Analysis name="test_separator">
		<A name="functional_unit">oil</A>
		<A name="energy_basis">LHV</A>
	  <A name="GWP_years">100</A>
	  <A name="GWP_version">AR5</A>
		<Field name="test"/>
	</Analysis>

	<Field name="test">
		<A name="country">USA</A>

		<Process class="Separation" desc="Test process 1">
			<Produces>crude oil</Produces>
		</Process>

		<Process class="Before" desc="Test process 2">
			<Consumes>crude oil</Consumes>
			<Consumes>hydrogen</Consumes>
			<Produces>natural gas</Produces>
		</Process>

		<Process class="After" desc="Test process 2">
			<Consumes>crude oil</Consumes>
			<Consumes>hydrogen</Consumes>
			<Produces>natural gas</Produces>
		</Process>

		<Process class="DownholePump"/>

		<Stream src="Separation" dst="After" name="oil after separator">
			<A name="temperature">90.0</A>
			<A name="pressure">100.0</A>
			<Component name="oil" phase="liquid">273.6926</Component>
			<Component name="H2O" phase="liquid">38.3170</Component>
		</Stream>

		<Stream src="Separation" dst="After" name="water after separator">
			<A name="temperature">90.0</A>
			<A name="pressure">100.0</A>
			<Component name="H2O" phase="liquid">1963.015</Component>
		</Stream>

		<Stream src="Separation" dst="After" name="gas after separator">
			<A name="temperature">90.0</A>
			<A name="pressure">500.0</A>
			<Component name="N2" phase="gas">4.8803</Component>
			<Component name="CO2" phase="gas">0.8848</Component>
			<Component name="C1" phase="gas">87.1392</Component>
			<Component name="C2" phase="gas">9.7080</Component>
			<Component name="C3" phase="gas">4.3515</Component>
			<Component name="C4" phase="gas">2.5138</Component>
			<Component name="H2S" phase="gas">0.0208</Component>
		</Stream>

		<Stream src="Separation" dst="Environment" name="gas fugitives from separator">
			<A name="temperature">60.0</A>
			<A name="pressure">14.7</A>
			<Component name="N2" phase="gas">0.001275</Component>
			<Component name="CO2" phase="gas">0.000231</Component>
			<Component name="C1" phase="gas">0.022765</Component>
			<Component name="C2" phase="gas">0.002536</Component>
			<Component name="C3" phase="gas">0.001137</Component>
			<Component name="C4" phase="gas">0.000657</Component>
			<Component name="H2S" phase="gas">0.000005</Component>
		</Stream>

		<Stream src="Before" dst="Separation" name="oil before separator"/>
		<Stream src="Before" dst="Separation" name="water before separator"/>
		<Stream src="Before" dst="Separation" name="gas before separator"/>


	</Field>
</Model>

=== RMI/OPGEEv4/tests/files/test_mcs.xml
<?xml version='1.0' encoding='UTF-8'?>
<Model xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../opgee/etc/opgee.xsd">

  <Analysis name="test-mcs">
    <A name="functional_unit">oil</A>
    <A name="GWP_horizon">100</A>
    <A name="GWP_version">AR5</A>

    <FieldRef name="test-mcs"/>
  </Analysis>

  <Field name="test-mcs">
    <A name="downhole_pump">0</A>
    <A name="water_reinjection">1</A>
    <A name="natural_gas_reinjection">1</A>
    <A name="water_flooding">0</A>
    <A name="gas_lifting">1</A>
    <A name="gas_flooding">0</A>
    <A name="steam_flooding">0</A>
    <A name="oil_sands_mine">None</A>
    <A name="country">Angola</A>
    <A name="name">Girassol</A>
  </Field>

</Model>

=== RMI/OPGEEv4/tests/files/test_gas_flooding.xml
<?xml version="1.0" encoding="UTF-8"?>
<Model xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../opgee/etc/opgee.xsd">

	<Analysis name="test_gas_flooding">
		<A name="functional_unit">gas</A>
		<A name="energy_basis">LHV</A>
	  <A name="GWP_horizon">100</A>
	  <A name="GWP_version">AR5</A>
		<Field name="test_gas_flooding"/>
	</Analysis>

    <Field name="test_gas_flooding">
        <A name="country">USA</A>
        <A name="gas_flooding">1</A>


        <Process class="Before" impute-start="true"/>
        <Process class="After"/>
        <Process class="GasReinjectionCompressor">
            <A name="flood_gas_type">NG</A>
        </Process>
        <Stream src="Before" dst="GasReinjectionCompressor" name="before to gas reinjection compressor" boundary="Production">
            <Contains>gas for gas reinjection compressor</Contains>
            <Component name="C1" phase="gas">10</Component>
            <A name="temperature">60</A>
            <A name="pressure">600</A>
        </Stream>

        <Stream src="GasReinjectionCompressor" dst="After" name="gas reinjection compressor to after">
            <Contains>imported gas</Contains>
            <Contains>gas for gas reinjection well</Contains>
        </Stream>

        <Stream src="GasReinjectionCompressor" dst="Environment" name="gas reinjection compressor to environment">
            <Contains>gas fugitives</Contains>
        </Stream>
    </Field>

</Model>

=== RMI/OPGEEv4/tests/files/test_model.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Working draft of XML file format -->
<!-- This file contains the standard OPGEEv4 LCA model. The metadata describing fields, options,
     and default values is found in attributes.xml. When creating a new model, the user can start
     with the standard model and add/delete/alter elements in a separate file, or simply save copy
     and modify this file. We also (will) support site- and user-specific XML template files that
     define custom starting points.
     -->
<Model xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../opgee/etc/opgee.xsd">
	<!-- these might belong in Analysis, or the two levels (Model, Analysis) might collapse into one -->
	<A name="GWP_years">100</A>
	<A name="GWP_version">AR5</A>
	<A name="functional_unit">oil</A>
	<A name="energy_basis">LHV</A>

	<Analysis name="default">
		<FunctionalUnit>oil</FunctionalUnit>
		<EnergyBasis>LHV</EnergyBasis>

		<Field name="test">
			<A name="country">USA</A>
			<A name="offshore">0</A>
			<A name="age">86</A>
			<A name="depth">4936</A>
			<A name="oil_prod">101295</A>
			<A name="num_prod_wells">41539</A>
			<A name="num_water_inj_wells">34426</A>
			<A name="well_diam">3.01</A>
			<A name="prod_index">37.53</A>
			<A name="res_press">887.31</A>
			<A name="res_temp">70.84</A>
			<A name="GOR">1205.4</A>

			<Process class="Proc1" desc="Test process 1">
				<Produces>crude oil</Produces>
			</Process>

			<Process class="Proc2" desc="Test process 2">
				<Consumes>crude oil</Consumes>
				<Consumes>hydrogen</Consumes>
				<Produces>natural gas</Produces>
			</Process>

			<Process class="Proc3" desc="Test process 3">
				<Consumes>natural gas</Consumes>
				<Produces>hydrogen</Produces>
				<Produces>CO2</Produces>
			</Process>

			<Process class="Proc4" desc="Test process 4">
				<Consumes>CO2</Consumes>
			</Process>

			<Stream src="Proc1" dst="Proc2">
				<A name="temperature">90.0</A>
				<A name="pressure">150.0</A>
				<Component name="oil" phase="liquid" unit="tonne/d">100</Component>
			</Stream>

			<!-- Creates a process loop -->
			<Stream src="Proc2" dst="Proc3"/>
			<Stream src="Proc3" dst="Proc2"/>
			<Stream src="Proc3" dst="Proc4"/>
		</Field>
	</Analysis>
</Model>
