=== RMI/OPGEEv4/opgee/etc/opgee.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs='http://www.w3.org/2001/XMLSchema' elementFormDefault='qualified'>
	
	<xs:element name='Model'>
		<xs:complexType>
			<xs:choice maxOccurs="2">
				<xs:element minOccurs='0' maxOccurs='1' ref="Analysis"/>
				<xs:element minOccurs='0' maxOccurs='1' ref='TechnologyDatabase'/>
			</xs:choice>
		</xs:complexType>
    </xs:element>
	
    <xs:element name='FunctionalUnit' type='xs:NCName'/>
    <xs:element name='EnergyBasis' type='xs:NCName'/>
	
	<xs:element name='Analysis'>
        <xs:complexType>
			<xs:choice maxOccurs='unbounded'>
                <xs:element minOccurs='1' maxOccurs='1' ref='FunctionalUnit'/>
                <xs:element minOccurs='1' maxOccurs='1' ref='EnergyBasis'/>
                <xs:element minOccurs='0' maxOccurs='unbounded' ref='Field'/>
                <xs:element ref='Variables'/>
            </xs:choice>
            <xs:attribute name='name' use='required' type='xs:NCName'/>
        </xs:complexType>
	</xs:element>
	
    <xs:element name='Variables'>
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs='unbounded' ref='A'/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
	
	<xs:element name='Field'>
        <xs:complexType>
            <xs:choice maxOccurs='unbounded'>
                <xs:element maxOccurs='unbounded' ref='A'/>
                <xs:element minOccurs='1' maxOccurs='unbounded' ref='Process'/>
            </xs:choice>
            <xs:attribute name='is_offshore' use='required' type='xs:NCName'/>
            <xs:attribute name='location' use='required' type='xs:NCName'/>
            <xs:attribute name='name' use='required' type='xs:NCName'/>
        </xs:complexType>
    </xs:element>
	
    <xs:element name='A'>
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base='xs:NMTOKEN'>
                    <xs:attribute name='name' use='required' type='xs:NCName'/>
                    <xs:attribute name='type' type='xs:NCName'/>
                    <xs:attribute name='unit'/>
                    <xs:attribute name='desc'/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
	</xs:element>
	
	<!-- use type forward reference to define recursive structure -->
	<xs:element name="Process" type="ProcessType"></xs:element>
	
	<xs:complexType name="ProcessType">
		<xs:choice maxOccurs="unbounded">
			<xs:element name="Process" type="ProcessType"/>
			<xs:element minOccurs='0' maxOccurs='unbounded' ref='A'/>
			<xs:element minOccurs='0' maxOccurs='unbounded' ref='Technology'/>	
			<xs:element minOccurs='0' maxOccurs='unbounded' ref='Option'/>
			<xs:element minOccurs='0' maxOccurs='unbounded' ref='Stream'/>			
		</xs:choice>
		<xs:attribute name='class' type='xs:NCName'/>
		<xs:attribute name='name' type='xs:NCName'/>
	</xs:complexType>
	
    <xs:element name='Option'>
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs='unbounded' ref='Technology'/>
            </xs:sequence>
            <xs:attribute name='default' use='required' type='xs:NCName'/>
            <xs:attribute name='name' use='required' type='xs:NCName'/>
            <xs:attribute name='selected' use='required' type='xs:NCName'/>
        </xs:complexType>
	</xs:element>
	
	<xs:element name='Temperature'>
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base='xs:decimal'>
                    <xs:attribute name='unit' use='required'/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
	</xs:element>	
	
	<xs:element name='Pressure'>
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base='xs:decimal'>
                    <xs:attribute name='unit' use='required'/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>	
	
    <xs:element name='Stream'>
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element ref='Temperature'/>
                <xs:element ref='Pressure'/>
                <xs:element ref='Component'/>
                <xs:element ref='Source'/>
                <xs:element ref='Destination'/>
            </xs:choice>
            <xs:attribute name='name' use='required'/>
            <xs:attribute name='number' use='required' type='xs:integer'/>
        </xs:complexType>
	</xs:element>
	
    <xs:element name='Phase' type='xs:NCName'/>
	
	<xs:element name='Rate'>
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base='xs:decimal'>
                    <xs:attribute name='unit' use='required'/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>	
	
	<xs:element name='Component'>
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element minOccurs="1" ref='Phase'/>
                <xs:element minOccurs="1" ref='Rate'/>
			</xs:choice>
			<xs:attribute name='name' use='required'/>
        </xs:complexType>
	</xs:element>
	
    <xs:element name='Source'>
        <xs:complexType>
            <xs:attribute name='name' use='required' type='xs:NCName'/>
        </xs:complexType>
    </xs:element>
	
	<xs:element name='Destination'>
        <xs:complexType>
            <xs:attribute name='fraction' type='xs:decimal'/>
            <xs:attribute name='name' use='required' type='xs:NCName'/>
        </xs:complexType>
    </xs:element>
	
	<xs:element name='Technology'>
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs='0' maxOccurs='unbounded' ref='A'/>
            </xs:sequence>
            <xs:attribute name='class' use='required' type='xs:NCName'/>
            <xs:attribute name='name' type='xs:NCName'/>			
        </xs:complexType>
	</xs:element>
	
	<xs:element name='TechnologyDatabase'>
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs='0' maxOccurs='unbounded' ref='Technology'/>
			</xs:sequence>
		</xs:complexType>		
	</xs:element>
	
</xs:schema>

=== RMI/OPGEEv4/tests/files/field_groups_model.xml
<?xml version="1.0" encoding="UTF-8"?>
<Model xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../opgee/etc/opgee.xsd">

	<Analysis name="test">
	  <A name="functional_unit">oil</A>
	  <A name="energy_basis">LHV</A>
	  <A name="GWP_horizon">100</A>
	  <A name="GWP_version">AR5</A>
	  <Group regex="1">.*Foo.*</Group>
	</Analysis>

	<Field name="test1">
		<Group>Foo</Group>
		<A name="country">USA</A>
		<Process class="After"/>

		<Process class="ProcA" desc="Test process 1"/>
		<Process class="ProcB" desc="Test process 2"/>
		<Process class="Boundary" boundary="Production"/>

		<Stream src="ProcB" dst="ProductionBoundary"/>
	</Field>

	<Field name="test2">
		<Group>MatchesFooAlso</Group>
		<A name="country">USA</A>

		<Process class="ProcA" desc="Test process 1"/>
		<Process class="ProcB" desc="Test process 2"/>
		<Process class="Boundary" boundary="Production"/>

		<Stream src="ProcB" dst="ProductionBoundary"/>
	</Field>

	<Field name="test3">
		<Group>Bar</Group>
		<A name="country">USA</A>

		<Process class="ProcA" desc="Test process 1"/>
		<Process class="ProcB" desc="Test process 2"/>
		<Process class="Boundary" boundary="Production"/>

		<Stream src="ProcB" dst="ProductionBoundary"/>
	</Field>

</Model>

=== RMI/OPGEEv4/opgee/mcs/etc/test-mcs-field.xml
<Model schema_version="4.0.0.a" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="opgee.xsd">
	<Analysis name="test">
		<A name="functional_unit">oil</A>
		<A name="GWP_horizon">100</A>
		<A name="GWP_version">AR5</A>
		<FieldRef name="test-field"/>
	</Analysis>

	<Field name="test-field" modifies="template">
		<A name="gas_flooding">0</A>
		<A name="steam_flooding">0</A>
		<A name="oil_sands_mine">None</A>
		<A name="country">CountryX</A>
		<A name="name">FieldX</A>
		<A name="fraction_elec_onsite">1.0</A>
		<A name="fraction_water_reinjected">1.0</A>
		<A name="frac_transport_tanker">1.0</A>
		<A name="frac_transport_barge">0.0</A>
		<A name="frac_transport_pipeline">0.0</A>
		<A name="frac_transport_rail">0.0</A>
		<A name="transport_dist_tanker">7984.0</A>
		<A name="transport_dist_barge">0.0</A>
		<A name="transport_dist_pipeline">0.0</A>
		<A name="transport_dist_rail">0.0</A>
  </Field>
</Model>
